name: Deploy Frontend to VPS

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          export NVM_DIR="/root/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use v22.19.0
          
          cd ${{ secrets.ROUTE }}
          echo "=== Frontend deployment en: $(pwd) ==="
          
          git pull
          npm install
          npm run build
          
          # Reiniciar nginx para servir nuevos archivos estáticos
          sudo systemctl restart nginx
          echo "=== Frontend desplegado ==="